version: "3.7"

name: gilgoblin

services:
  gilgoblin-database:
    image: nickreinlein/gilgoblin-database
    container_name: database
    environment:
      POSTGRES_DB: gilgoblin
      POSTGRES_USER: gilgoblin
      POSTGRES_PASSWORD: gilgoblin
      PGUSER: gilgoblin
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "5432:5432"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./src/Database/db:/var/lib/postgresql/data
      - ./src/Database/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  gilgoblin-api:
    image: nickreinlein/gilgoblin-api
    container_name: api
    depends_on:
      - gilgoblin-database
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "55448:80"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

  gilgoblin-dataupdater:
    image: nickreinlein/gilgoblin-dataupdater
    container_name: dataupdater
    depends_on:
      - gilgoblin-database
      - gilgoblin-api
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

  gilgoblin-accountant:
    image: nickreinlein/gilgoblin-accountant
    container_name: accountant
    depends_on:
      - gilgoblin-database
      - gilgoblin-api
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

  gilgoblin-frontend:
    image: nickreinlein/gilgoblin-frontend
    container_name: frontend
    ## For local testing, replace with:
    # image: frontend
    # build: src/frontend/
    depends_on:
      - gilgoblin-database
      - gilgoblin-api
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "3000:3000"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

  gilgoblin-prometheus:
    image: prom/prometheus
    container_name: prometheus
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "127.0.0.1:9090:9090"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./benchmarks:/etc/prometheus
    restart: unless-stopped

  gilgoblin-node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "9100:9100"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./benchmarks:/etc/node-exporter
    restart: unless-stopped

  gilgoblin-grafana:
    image: grafana/grafana
    container_name: grafana
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      - gilgoblin
    ports:
      - "55450:3000"
    volumes:
      - ./benchmarks/grafana:/var/lib/grafana   
    restart: unless-stopped

  gilgoblin-k6-benchmarks:
    image: grafana/k6
    container_name: k6-benchmarks
    depends_on:
      - gilgoblin-database
      - gilgoblin-api
    command: run /scripts/crafts-benchmark.js
    networks:
      - gilgoblin
    ports:
      - "6565:6565"
    volumes:
      - ./benchmarks:/scripts
    restart: no

networks:
  gilgoblin:
