version: "3.7"

name: gilgoblin

services:
  gilgoblin-database:
    # image: nickreinlein/gilgoblin-database
    image: database
    build: src/Database/
    container_name: database
    environment:
      POSTGRES_DB: gilgoblin
      POSTGRES_USER: gilgoblin
      POSTGRES_PASSWORD: gilgoblin
      PGUSER: gilgoblin
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin
    ports:
      - "5432:5432"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./src/Database/db:/var/lib/postgresql/data
      - ./src/Database/resources:/docker-entrypoint-initdb.d
    restart: unless-stopped

  gilgoblin-api:
    # image: nickreinlein/gilgoblin-api
    image: api
    build: src/Api/
    container_name: api
    depends_on:
      - gilgoblin-database
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin      
    ports:
      - "55448:80"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

  # gilgoblin-dataupdater:
  #   image: nickreinlein/gilgoblin-dataupdater
  #   container_name: dataupdater
  #   depends_on:
  #     - gilgoblin-database
  #     - gilgoblin-api
  #   healthcheck:
  #     test: [ "CMD-SHELL" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - gilgoblin  
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '50m'
  #   restart: unless-stopped


  gilgoblin-accountant:
    # image: nickreinlein/gilgoblin-accountant
    build: src/Accountant/
    container_name: accountant
    depends_on:
      - gilgoblin-database
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gilgoblin  
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped

networks:
  gilgoblin: