ersion: "3.7"

services:
  gilgoblin-api:
    image: gilgoblin-api
    build: ./
    container_name: api
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "55448:80"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    restart: unless-stopped