name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: gilgoblin_db
          POSTGRES_USER: gilgoblin
          POSTGRES_PASSWORD: placeholder_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -d gilgoblin_db -U gilgoblin"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # - name: Debug Secrets
      #   run: |
      #     echo "POSTGRES_PASSWORD=12312321"
      #     echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
      #     echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
      #     echo "Connection String=${{ secrets.DB_CONNECTION_STRING }}"
      #   shell: bash

      - name: Setup .NET8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # - name: Set DB Connection String
      #   id: set-connection-string
      #   run: |
      #     echo "DB_CONNECTION_STRING=Host=localhost;Port=5432;Database=gilgoblin_db;Username=gilgoblin;Password=${{ secrets.POSTGRES_PASSWORD }};" >> $GITHUB_ENV

      - name: Test
        env: ConnectionStrings__GilGoblinDbContext:"Host=localhost;Port=5432;Database=gilgoblin_db;Username=gilgoblin;Password=placeholder_password;"
        run: dotnet test --no-build --verbosity detailed --filter "Category!=Component"
